name: 'git-commit-push'
description: 'Adds, commits, and pushes changes with a custom commit message.'
inputs:
  message:
    description: 'Commit message'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check for changes
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      shell: pwsh
      id: status
      run: |
        if ($null -ne (git status --porcelain)) {
          echo "Changes detected, committing and pushing changes"
          echo "has_changes=1" >> $env:GITHUB_OUTPUT
        }
        else {
          echo "No changes detected, skipping commit and push"
          echo "has_changes=0" >> $env:GITHUB_OUTPUT
        }
    - name: Commit and push changes
      if: steps.status.outputs.has_changes == '1'
      shell: pwsh
      env:
        MESSAGE: ${{ inputs.message }}
      run: |
        git add --verbose .
        git config user.name 'gittools-bot'
        git config user.email 'gittoolsbot@outlook.com'
        git commit -m $env:MESSAGE --allow-empty
        git push --force
