version: 2
updates:
- package-ecosystem: github-actions
  labels:
    - "dependencies (github-actions)"
  commit-message:
    prefix: "(github-actions)"
  directories:
    - checkout/
    - choco-creds/
    - dockerhub-creds/
    - github-app-creds/
    - git-commit-push/
    - nuget-creds/
    - tfx-creds/
  schedule:
    interval: cron
    cronjob: "0 12 * * *"
  groups:
    actions:
      patterns:
        - "*"
      group-by: dependency-name
