name: 'Load DockerHub Secrets'
description: 'Loads DockerHub credentials from 1Password'

inputs:
  op_service_account_token:
    description: '1Password service account token'
    required: true

outputs:
  docker_username:
    description: DockerHub username
    value: ${{ steps.load.outputs.docker_username }}
  docker_password:
    description: DockerHub password
    value: ${{ steps.load.outputs.docker_password }}

runs:
  using: 'composite'
  steps:
    - name: Load secrets from 1Password
      id: load
      uses: 1password/load-secrets-action@v4.1.1
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.op_service_account_token }}
        docker_username: op://gittools/ci/dockerhub/username
        docker_password: op://gittools/ci/dockerhub/token
